---
# See https://github.com/rubocop/rubocop/blob/master/config/default.yml for all
# options
require:
  - rubocop-rake
  - rubocop-rspec

AllCops:
  DisplayCopNames: true
  NewCops: enable
  TargetRubyVersion: 3.3

Layout/LineLength:
  AllowHeredoc: true
  AllowURI: true
  AutoCorrect: true
  Exclude:
    - ynab_convert.gemspec
  Max: 80

Metrics/BlockLength:
  Exclude:
    - Guardfile
    - ynab_convert.gemspec
    - 'spec/**/*_spec.rb'

Metrics/MethodLength:
  Max: 25

Metrics/AbcSize:
  Enabled: false
